SCREEN_W = 480
SCREEN_H = 320

CENTER_X = 240
CENTER_Y = 160

MARGIN_LEFT = 18
MARGIN_RIGHT = 18
MARGIN_TOP = 14
MARGIN_BOTTOM = 14

SCALE_LEFT = 18
SCALE_RIGHT = 462
SCALE_WIDTH = SCALE_RIGHT - SCALE_LEFT

CONTENT_LEFT = 26
CONTENT_RIGHT = 454
CONTENT_WIDTH = CONTENT_RIGHT - CONTENT_LEFT

# Equal top/bottom scales
SCALE_GLASS_X = 10
SCALE_GLASS_W = 460
SCALE_GLASS_H = 78

TOP_SCALE_Y = 14
TOP_SCALE_BOTTOM = TOP_SCALE_Y + SCALE_GLASS_H

BOTTOM_SCALE_Y = SCREEN_H - MARGIN_BOTTOM - SCALE_GLASS_H
BOTTOM_SCALE_BOTTOM = BOTTOM_SCALE_Y + SCALE_GLASS_H

# Top scale (genres)
GENRE_GLASS_X = SCALE_GLASS_X
GENRE_GLASS_Y = TOP_SCALE_Y
GENRE_GLASS_W = SCALE_GLASS_W
GENRE_GLASS_H = SCALE_GLASS_H

GENRE_TOP = GENRE_GLASS_Y
GENRE_HEIGHT = GENRE_GLASS_H
GENRE_BOTTOM = GENRE_GLASS_Y + GENRE_GLASS_H

GENRE_BASELINE_Y = GENRE_GLASS_Y + 50
GENRE_LABEL_Y = GENRE_GLASS_Y + 18

GENRE_TICK_SHORT_H = 8
GENRE_TICK_MEDIUM_H = 12
GENRE_TICK_LONG_H = 16

# Bottom scale (stations)
STATION_GLASS_X = SCALE_GLASS_X
STATION_GLASS_Y = BOTTOM_SCALE_Y
STATION_GLASS_W = SCALE_GLASS_W
STATION_GLASS_H = SCALE_GLASS_H

STATION_TOP = STATION_GLASS_Y
STATION_HEIGHT = STATION_GLASS_H
STATION_BOTTOM = STATION_GLASS_Y + STATION_GLASS_H

STATION_BASELINE_Y = STATION_GLASS_Y + 50
STATION_LABEL_Y = STATION_GLASS_Y + 10

STATION_TICK_SHORT_TOP = STATION_BASELINE_Y - 12
STATION_TICK_MEDIUM_TOP = STATION_BASELINE_Y - 20
STATION_TICK_LONG_TOP = STATION_BASELINE_Y - 34
STATION_TICK_BOTTOM = STATION_BASELINE_Y

ACTIVE_WINDOW_W = 96
ACTIVE_WINDOW_LEFT = CENTER_X - ACTIVE_WINDOW_W // 2
ACTIVE_WINDOW_RIGHT = CENTER_X + ACTIVE_WINDOW_W // 2

# Center information panel
INFO_TOP = 104
INFO_BOTTOM = 216
INFO_HEIGHT = INFO_BOTTOM - INFO_TOP

INFO_PANEL_X = 42
INFO_PANEL_Y = INFO_TOP
INFO_PANEL_W = 396
INFO_PANEL_H = INFO_HEIGHT

CLOCK_Y = 120
STATION_NAME_Y = 164
INDICATORS_Y = 196

# Cursor
CURSOR_X = CENTER_X
CURSOR_TOP = TOP_SCALE_Y + 8
CURSOR_BOTTOM = BOTTOM_SCALE_BOTTOM - 8
CURSOR_LINE_W = 2

# Split cursor segments
CURSOR_SEGMENT_W = 4
TOP_CURSOR_Y1 = TOP_SCALE_Y + 10
TOP_CURSOR_Y2 = TOP_SCALE_Y + SCALE_GLASS_H - 10
BOTTOM_CURSOR_Y1 = BOTTOM_SCALE_Y + 10
BOTTOM_CURSOR_Y2 = BOTTOM_SCALE_Y + SCALE_GLASS_H - 10

# Center panel decoration
INFO_INNER_MARGIN = 12
INFO_DECOR_LINE_Y_TOP = INFO_PANEL_Y + 14
INFO_DECOR_LINE_Y_BOTTOM = INFO_PANEL_Y + INFO_PANEL_H - 14

# Fonts
FONT_SMALL = 12
FONT_GENRE = 14
FONT_STATION = 18
FONT_STATION_SMALL = 16
FONT_CLOCK = 34
FONT_CENTER_TITLE = 30
FONT_DECOR = 10

# Scale item default widths
GENRE_ITEM_W = 88
STATION_ITEM_W = 128
